### ISSUE TITLE
Only 1/1/2014 to 31/12/2014 born students are allowed to add into the system. it should be corrected as in the below comment

### ISSUE THREAD

**Issue by NaduniRanasinghe** [moe-lk/sis#13]
Grade 1
Now - The student should be 5 years old
Correct - The student should be 5 or more than 5 years old

Grade 2
Now - The student should be 6 years old
Correct - The student should be 6 or more than 6 years old

Grade 3 
Now - The student should be 7 years old
Correct - The student should 7 or more than 7 years old

Grade 4
Now - The student should be 8 years old
Correct The should be 8 or more than 8 years old

Grade 5 
Now - The student should be 9 years old
Correct -The student should be 9 or more than 9 years old

**Comment by mohamednizar** [comment]
This can be configured by adding the minimum age limit to 5 years and set the upper boundary  to 5+ , in the System Configuration there is an option for set student Admission age limit.
