### ISSUE TITLE
Any provincial Coordinator should not be able to add a zonal coordinator to any zone in the system. 

### ISSUE THREAD

**Issue by NaduniRanasinghe** [moe-lk/sis#15]
Example:
Eastern Province coordinator should be able to add zonal coordinators to his province only. but the current system allows Provincial Coordinators to add zonal coordinators to not only his province but any province in the system.

**Comment by mohamednizar** [comment]
Can the Newly add Coordinate access the privileges given by the Provincial Coordinator?

**Comment by mohamednizar** [comment]
This can be handled by ordering user roles in the system.
