### ISSUE TITLE
There is an error occurred when adding a national school, because 'Area' in the form is requested as a Zone, but there is only 'National Schools -Province' in select options

### ISSUE THREAD

**Issue by NaduniRanasinghe** [moe-lk/sis#19]

**Comment by mohamednizar** [comment]
National Schools has been created as a Province, We can create all Provinces and Zone under national schools. If Provincial Coordinator needs to access the national schools,  the permissions for National schools under zone can be assign. 

Something like what we have done for provincial schools under all island, we have to redo the same thing under national schools.
