### ISSUE TITLE
No Administrative areas (Zones) under National Schools Category

### ISSUE THREAD

**Issue by NaduniRanasinghe** [moe-lk/sis#20]

**Comment by mohamednizar** [comment]
We can move the National Schools under regular administrative and area level. That's the way to implement this. So National Schools go under the regular category and we have to classify national or provincial by another option in institute general information. Sector/Provider/Type. these options are available, we have to configure them on the environment.

**Comment by mohamednizar** [comment]
Now we can access the administrative areas under national schools.
