### ISSUE TITLE
can't add new staff members,There are no select options for staff type and position

### ISSUE THREAD

**Issue by pasan04-zz** [moe-lk/sis#21]
![capture9](https://user-images.githubusercontent.com/28913349/51818374-aceba600-22f4-11e9-8fbe-abaaeaccf411.PNG)

**Comment by mohamednizar** [comment]
In this position tab, we have to create a positions

**Comment by mohamednizar** [comment]
Staff Types can be added to the Field options menu. I'm working on Positions. In the Position Tab , we have to create positions.

**Comment by mohamednizar** [comment]
Now we can create positions and staff in the system.
