### ISSUE TITLE
Add new fields in Add new student form

### ISSUE THREAD

**Issue by NaduniRanasinghe** [moe-lk/sis#31]
Pre-school Education 
This can be added by changing the field name special needs or special education as Preschool Education
There should be two options to select (Yes or No)
This should be changed in the backend

Special Education 
Options for this field can be added from the front end

**Comment by mohamednizar** [comment]
The system is capable to handle pre-school information from the basic level, No need to get such an option since the system can be implemented for preschools as well. So we have to plan to implement pre-school information as well.

The Special Education Options are added
