### ISSUE TITLE
Base table or view already exists: 1050 Table 'uploads' already exists

### ISSUE THREAD

**Issue by anjula-sack** [moe-lk/sis#76]
- I can't setup the project. I keep getting this error. I tried adding a dump multiple times.
### To Reproduce:
`sudo docker-compose up`

- PHP version : 7.3.11
- Laravel version : 5.8.35
- OS : Ubuntu 19.10 

error
```
Configuring the database
sis-bulk-upload_1  | Migrating: 2019_07_18_081941_file_upload
sis-bulk-upload_1  | 
sis-bulk-upload_1  |    Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'uploads' already exists (SQL: create table `uploads` (`id` int unsigned not null auto_increment primary key, `security_user_id` int not null, `institution_class_id` int not null, `model` varchar(191) not null, `filename` varchar(191) not null, `is_processed` tinyint(1) not null default '0', `deleted_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')
sis-bulk-upload_1  | 
sis-bulk-upload_1  |   at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
sis-bulk-upload_1  |     660|         // If an exception occurs when attempting to run a query, we'll format the error
sis-bulk-upload_1  |     661|         // message to include the bindings with SQL, which will make this exception a
sis-bulk-upload_1  |     662|         // lot more helpful to the developer instead of just the database's errors.
sis-bulk-upload_1  |     663|         catch (Exception $e) {
sis-bulk-upload_1  |   > 664|             throw new QueryException(
sis-bulk-upload_1  |     665|                 $query, $this->prepareBindings($bindings), $e
sis-bulk-upload_1  |     666|             );
sis-bulk-upload_1  |     667|         }
sis-bulk-upload_1  |     668| 
sis-bulk-upload_1  | 
sis-bulk-upload_1  |   Exception trace:
sis-bulk-upload_1  | 
sis-bulk-upload_1  |   1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'uploads' already exists")
sis-bulk-upload_1  |       /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
sis-bulk-upload_1  | 
sis-bulk-upload_1  |   2   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'uploads' already exists")
sis-bulk-upload_1  |       /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
sis-bulk-upload_1  | 
sis-bulk-upload_1  |   Please use the argument -v to see more details.
```

**Comment by anjula-sack** [comment]
I tried this solution : https://stackoverflow.com/questions/48744687/laravel-5-6-table-creation-failed

**Comment by jayasanka-sack** [comment]
@anjula-sack What are the other solutions you have tried? 

> I tried adding a dump multiple times.

This isn't clear for me

**Comment by anjula-sack** [comment]
I import the dump in 20190205 and another dump given by janith. @jayasanka-sack

**Comment by jayasanka-sack** [comment]
I have no idea about this project, but after a couple of experiments, I figured out a way. Importing the last dump will resolve this issue. 

1. Terminate the current process. 

1. Start the `sis-mysql` docker container. It will run on the port `8106`.
     ```bash
     $ docker start sis-mysql
     ```
1. Connect to the sis-mysql server. Use the password `secret` when prompted if you haven't changed anything.
      ```bash
      $ mysql -u root -p -h 0.0.0.0 --port 8106
      ```
1. Drop the database named `openemis` and recreate it and exit from the mysql console. This is to remove all the tables created during the process.
      ```mysql
      DROP DATABASE openemis;
      CREATE DATABASE openemis;
      exit;
      ```
2. Navigate to the latest dump. `Dump20190205-1` in this case. (hopefully 😇)
      ```bash
      $ cd mysql/Dump20190205-1
      ```

3. Concat all files to a single SQL file. (I created a file with a different extension and then changed it to .sql format later because it might cause an infinite loop 😀)
      ```bash
      $ cat *.sql > temp.sql1 
      $ mv temp.sql1 temp.sql
      ```
1. Import the dump.
    ```bash
    $ mysql -u root -p -h 0.0.0.0 --port 8106  openemis < temp.sql
    ```
1. Remove the temporaraly created file

    ```
     $ rm temp.sql
    ```

1. Navigate to the project root and open up the project.
    ```
    $ cd path/to/the/project
    $ docker-compose up
    ```

1. The NEMIS will be up and running at http://0.0.0.0:8180/ 😇

1. Enjoy!!! 🍻😁

**Comment by anjula-sack** [comment]
Thanks this solution worked for me. but I got ```Cache engine Cake\Cache\Engine\FileEngine is not properly configured.``` error. I fixed this by this. 
 `$ chmod 777 sis  -R`

**Comment by jayasanka-sack** [comment]
`Cache engine Cake\Cache\Engine\FileEngine is not properly configured.`  
This issue isn't relevant to the above issue. It will resolve by giving write access to `temp` & `logs` directory in `sis-php/app/` directory
